# Generated by Django 4.2.6 on 2023-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModeName', models.CharField(blank=True, max_length=50, null=True)),
                ('ModeDesc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
