# Generated by Django 4.2.4 on 2023-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_trackingdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeDesc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
