# Generated by Django 4.2.6 on 2023-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_addressdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdb',
            name='IDNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
