# Generated by Django 4.2.6 on 2023-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_addressdb_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdb',
            name='TrackingId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
