# Generated by Django 4.2.4 on 2023-11-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_trackingdb_trackingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressdb',
            name='Website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
