# Generated by Django 4.2.4 on 2023-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_addressdb_email_alter_addressdb_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdb',
            name='Videos',
            field=models.FileField(blank=True, null=True, upload_to='sample'),
        ),
    ]
