# Generated by Django 4.2.4 on 2023-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_addressdb_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeVideo', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
        migrations.DeleteModel(
            name='AddressDB',
        ),
    ]
