# Generated by Django 4.2.4 on 2023-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_videodb_delete_addressdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodb',
            name='VideoName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
