# Generated by Django 4.2.4 on 2023-11-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_videodb_videoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodb',
            name='VideoName',
        ),
    ]
