# Generated by Django 4.2.4 on 2023-11-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_remove_videodb_videoname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('ContactNum', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
