# Generated by Django 4.2.4 on 2023-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_addressdb_contactnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedb',
            name='ModeImage',
            field=models.ImageField(blank=True, null=True, upload_to='ICNS'),
        ),
    ]
