# Generated by Django 4.2.4 on 2023-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_alter_modedb_modedesc_alter_typedb_typedesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('Social_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Social_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Social_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Social_4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
