# Generated by Django 4.2.4 on 2023-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_teamdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hub', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
