# Generated by Django 4.2.4 on 2023-11-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_locationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='locations'),
        ),
    ]
