# Generated by Django 4.2.4 on 2023-11-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_locationdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdb',
            name='Image',
        ),
    ]
