# Generated by Django 4.2.4 on 2023-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_remove_locationdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdb',
            name='StorageId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
