# Generated by Django 4.2.4 on 2023-11-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_shippingid_generator_warehouseid_generator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingID_Generator',
            new_name='Shipping_ID_Generator',
        ),
        migrations.RenameModel(
            old_name='WarehouseID_Generator',
            new_name='Warehouse_ID_Generator',
        ),
    ]
