# Generated by Django 4.2.4 on 2023-12-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_rename_shippingid_generator_shipping_id_generator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_ID_Generator',
        ),
        migrations.DeleteModel(
            name='Warehouse_ID_Generator',
        ),
    ]
