# Generated by Django 4.2.4 on 2023-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_delete_shipping_id_generator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdb',
            name='Copy_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
