# Generated by Django 4.2.4 on 2023-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_addressdb_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedb',
            name='TypeDesc_P1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typedb',
            name='TypeDesc_P2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typedb',
            name='TypeDesc_P3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typedb',
            name='TypeDesc_P4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typedb',
            name='TypeDesc_P5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
