# Generated by Django 4.2.4 on 2023-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_typedb_typedesc_p1_typedb_typedesc_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modedb',
            name='ModeDesc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modedb',
            name='ModeDesc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modedb',
            name='ModeDesc3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modedb',
            name='ModeDesc4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modedb',
            name='ModeDesc5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
