# Generated by Django 4.2.4 on 2023-12-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_modedb_modedesc1_modedb_modedesc2_modedb_modedesc3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modedb',
            old_name='ModeDesc1',
            new_name='ModeDesc_P1',
        ),
        migrations.RenameField(
            model_name='modedb',
            old_name='ModeDesc2',
            new_name='ModeDesc_P2',
        ),
        migrations.RenameField(
            model_name='modedb',
            old_name='ModeDesc3',
            new_name='ModeDesc_P3',
        ),
        migrations.RenameField(
            model_name='modedb',
            old_name='ModeDesc4',
            new_name='ModeDesc_P4',
        ),
        migrations.RenameField(
            model_name='modedb',
            old_name='ModeDesc5',
            new_name='ModeDesc_P5',
        ),
    ]
