# Generated by Django 4.2.4 on 2023-11-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_delete_addressdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
