# Generated by Django 4.2.4 on 2023-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_contactusdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('CfPassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
