# Generated by Django 4.2.4 on 2023-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_signupdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImages'),
        ),
    ]
