# Generated by Django 4.2.4 on 2023-11-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_signupdb_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='Profile',
        ),
    ]
