# Generated by Django 4.2.4 on 2023-11-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_remove_signupdb_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='pfofilepics'),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
