# Generated by Django 4.2.4 on 2023-11-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_profiledb_remove_signupdb_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledb',
            old_name='City',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='profiledb',
            old_name='Website',
            new_name='Hub',
        ),
    ]
