# Generated by Django 4.2.4 on 2023-11-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_rename_city_profiledb_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='Image',
        ),
    ]
