# Generated by Django 4.2.4 on 2023-11-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_rename_country_profiledb_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledb',
            old_name='Password',
            new_name='Country',
        ),
    ]
