# Generated by Django 4.2.4 on 2023-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_rename_password_profiledb_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Dep_Date', models.CharField(blank=True, max_length=100, null=True)),
                ('PromoCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
