# Generated by Django 4.2.4 on 2023-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_shipdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipdb',
            old_name='From',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='shipdb',
            old_name='PromoCode',
            new_name='End_Date',
        ),
        migrations.RenameField(
            model_name='shipdb',
            old_name='To',
            new_name='From_Date',
        ),
        migrations.AddField(
            model_name='shipdb',
            name='Promo_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipdb',
            name='Start_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipdb',
            name='To_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
