# Generated by Django 4.2.4 on 2023-11-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_rename_from_shipdb_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipdb',
            name='Action',
        ),
    ]
