# Generated by Django 4.2.4 on 2023-11-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_remove_shipdb_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipdb',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='shipdb',
            name='Start_Date',
        ),
    ]
