# Generated by Django 4.2.4 on 2023-11-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0018_remove_shipdb_end_date_remove_shipdb_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.CharField(blank=True, max_length=100, null=True)),
                ('EndDate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
