# Generated by Django 4.2.6 on 2023-11-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0019_warehousedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdb',
            name='WarehouseID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
