# Generated by Django 4.2.6 on 2023-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0020_trackingdb_warehouseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
