# Generated by Django 4.2.4 on 2023-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0022_shipdb_class_shipdb_type_shipdb_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdb',
            name='Order_Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipdb',
            name='ShippingID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
