# Generated by Django 4.2.4 on 2023-11-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0023_shipdb_order_status_shipdb_shippingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipdb',
            old_name='ShippingID',
            new_name='Shipping_ID',
        ),
    ]
