# Generated by Django 4.2.4 on 2023-11-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0026_classstorage_orderstorage_weightstorage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedb',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
