# Generated by Django 4.2.4 on 2023-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0027_warehousedb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedb',
            name='Order_Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousedb',
            name='Warehouse_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
