# Generated by Django 4.2.4 on 2023-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0028_warehousedb_order_status_warehousedb_warehouse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonaialsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='Testimonials')),
                ('Proffession', models.CharField(blank=True, max_length=255, null=True)),
                ('Testimonial', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
