# Generated by Django 4.2.4 on 2023-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0030_remove_signupdb_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileDb',
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
