# Generated by Django 4.2.4 on 2023-11-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0031_delete_profiledb_signupdb_address_signupdb_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='CfPassword',
        ),
    ]
