# Generated by Django 4.2.4 on 2023-11-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0033_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='Hub',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='State',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
