# Generated by Django 4.2.4 on 2023-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0038_remove_signupdb_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdb',
            old_name='Name',
            new_name='FName',
        ),
        migrations.AddField(
            model_name='signupdb',
            name='LName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
