# Generated by Django 4.2.4 on 2023-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0039_rename_name_signupdb_fname_signupdb_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
