# Generated by Django 4.2.4 on 2023-12-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0040_signupdb_address_signupdb_city_signupdb_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='City',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='State',
        ),
    ]
