# Generated by Django 4.2.4 on 2023-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0043_alter_signupdb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedb',
            name='Hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
