# Generated by Django 4.2.4 on 2023-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0045_shipdb_email_warehousedb_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipdb',
            old_name='From_Date',
            new_name='From_Address',
        ),
        migrations.RenameField(
            model_name='shipdb',
            old_name='To_Date',
            new_name='To_Address',
        ),
        migrations.AddField(
            model_name='shipdb',
            name='Est_Del_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
