# Generated by Django 4.2.4 on 2023-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0048_rename_fname_signupdb_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
