# Generated by Django 4.2.4 on 2023-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0050_signupdb_proimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainbodyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Top_Heading', models.CharField(blank=True, max_length=255, null=True)),
                ('Main_Heading', models.CharField(blank=True, max_length=255, null=True)),
                ('Content_P1', models.TextField(blank=True, null=True)),
                ('Content_P2', models.TextField(blank=True, null=True)),
                ('Content_P3', models.TextField(blank=True, null=True)),
                ('Content_P4', models.TextField(blank=True, null=True)),
                ('Content_P5', models.TextField(blank=True, null=True)),
                ('Sub_Heading', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testimonaialsdb',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
