# Generated by Django 4.2.4 on 2023-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0051_mainbodydb_testimonaialsdb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusdb',
            name='Subject',
        ),
        migrations.AddField(
            model_name='contactusdb',
            name='Proffession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
