# Generated by Django 4.2.4 on 2023-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0052_remove_contactusdb_subject_contactusdb_proffession'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='Pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
