# Generated by Django 4.2.4 on 2023-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0053_signupdb_address_signupdb_country_signupdb_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonaialsdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
