# Generated by Django 4.2.4 on 2023-12-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0054_testimonaialsdb_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdb',
            old_name='Hub',
            new_name='Proffession',
        ),
    ]
